### ISSUE TITLE
Create page on how to contribute

### ISSUE THREAD

**Issue by Omkar-Ajnadkar** [IIITKalyaniFOSC/iiitkalyanifosc.github.io#12]
There should be one page on the website on step by step guide on how to make a contribution with the help of required commands and photos to explain.
You can use README in this repo [https://github.com/Roshanjossey/first-contributions](https://github.com/Roshanjossey/first-contributions) by making some changes.
What say?

**Comment by anubhavp28** [comment]
@Omkar-Ajnadkar I am working on it for quite some time now! My thought was to create a complete tutorial on Git & Github, on our website. I looked at the tutorials already available on the web - either they are too complex to understand, or they just brush over things and ask readers to just remember commands. I am looking for a tutorial just in between.

**Comment by Omkar-Ajnadkar** [comment]
No problem, I just wanted to have some form of guide for contribution on the website. If you are creating this, then it is a great thing. Keep working on it!
