### ISSUE TITLE
Make the "Join Now" page

### ISSUE THREAD

**Issue by PulkitMishra** [IIITKalyaniFOSC/iiitkalyanifosc.github.io#16]
Page should include

- Link to Slack's sign up page.
- Link to IIIT Kalyani's slack workspace.
- Instructing people willing to join to introduce themselves in the intro channel of IIIT Kalyani's slack workspace mentioning their
1.  Name
2. Year
3. Skills
4. GitHub id

**Comment by Omkar-Ajnadkar** [comment]
Also, write to mention their GitHub id...

**Comment by anubhavp28** [comment]
@PulkitMishra Can you make the "join now" page - a page with instructions for a newcomer to join fosc?

**Comment by PulkitMishra** [comment]
@anubhanp28 on it .

**Comment by PulkitMishra** [comment]
@anubhavp28 close the issue?
