### ISSUE TITLE
Separate CSS, JS and HTML

### ISSUE THREAD

**Issue by PulkitMishra** [IIITKalyaniFOSC/iiitkalyanifosc.github.io#7]
Possibly, create separate directories for CSS( /css ) and Javascript( /js ). WIll save us from writing the same code again and again. Help needed with already pushed code - expected a PR that correctly segregate CSS & JS.

**Comment by zeus0789** [comment]
@PulkitMishra Okay will keep this in mind

**Comment by anubhavp28** [comment]
@PulkitMishra Since you started it, can you work on separating CSS/JS?

**Comment by PulkitMishra** [comment]
Sure.
